import { useMemo } from 'react'
import { useTamiStore } from '../store/useTamiStore'

const COLORS = ['#f9d342', '#5ab4e5', '#88c057', '#f87171', '#a78bfa', '#f97316']

function randomBetween(min: number, max: number) {
  return min + Math.random() * (max - min)
}

interface ConfettiPiece {
  id: number
  left: number
  delay: number
  duration: number
  color: string
  size: number
}

export function ChallengeSuccess() {
  const challengeSolved = useTamiStore((s) => s.challengeSolved)
  const challengeImageUrl = useTamiStore((s) => s.challengeImageUrl)
  const leaderboardPosition = useTamiStore((s) => s.leaderboardPosition)
  const dismissChallenge = useTamiStore((s) => s.dismissChallenge)

  const confetti: ConfettiPiece[] = useMemo(
    () =>
      Array.from({ length: 60 }, (_, i) => ({
        id: i,
        left: randomBetween(0, 100),
        delay: randomBetween(0, 2),
        duration: randomBetween(2, 5),
        color: COLORS[i % COLORS.length],
        size: randomBetween(6, 12),
      })),
    [],
  )

  if (!challengeSolved) return null

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.85)',
        zIndex: 1000,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
      }}
    >
      {/* Confetti */}
      {confetti.map((p) => (
        <div
          key={p.id}
          style={{
            position: 'absolute',
            left: `${p.left}%`,
            top: '-20px',
            width: p.size,
            height: p.size,
            background: p.color,
            borderRadius: Math.random() > 0.5 ? '50%' : '0',
            animation: `confettiFall ${p.duration}s ${p.delay}s ease-in infinite`,
          }}
        />
      ))}

      {/* Modal */}
      <div
        style={{
          position: 'relative',
          background: '#1a1a2e',
          border: '2px solid #f9d342',
          borderRadius: 16,
          padding: 32,
          maxWidth: 360,
          width: '90%',
          textAlign: 'center',
          zIndex: 1,
        }}
      >
        <div style={{ fontSize: 48, marginBottom: 8 }}>🎉</div>
        <h2 style={{ color: '#f9d342', marginBottom: 8, fontSize: 20 }}>
          Du hast Tami gehackt!
        </h2>

        {leaderboardPosition !== null && (
          <div style={{ color: '#a0aec0', fontSize: 14, marginBottom: 16 }}>
            Du bist Platz #{leaderboardPosition} auf der Bestenliste!
          </div>
        )}

        {challengeImageUrl && (
          <img
            src={challengeImageUrl}
            alt="Generated by Tami"
            style={{
              width: '100%',
              borderRadius: 12,
              marginBottom: 16,
              border: '2px solid #f9d342',
            }}
          />
        )}

        <p style={{ color: '#a0aec0', fontSize: 13, marginBottom: 20, lineHeight: 1.5 }}>
          Tami hat dein Bild generiert. Schau mal in die Bestenliste!
        </p>

        <button
          onClick={dismissChallenge}
          style={{
            padding: '10px 24px',
            background: '#f9d342',
            color: '#1a1a2e',
            border: 'none',
            borderRadius: 8,
            fontWeight: 700,
            fontSize: 14,
            cursor: 'pointer',
          }}
        >
          Schließen
        </button>
      </div>

      <style>{`
        @keyframes confettiFall {
          0% { transform: translateY(0) rotate(0deg); opacity: 1; }
          100% { transform: translateY(110vh) rotate(720deg); opacity: 0; }
        }
      `}</style>
    </div>
  )
}
