import { useMemo, useState } from 'react'
import { api } from '../api'
import { useTamiStore } from '../store/useTamiStore'

const CONFETTI_COLORS = ['#39d353', '#f5c842', '#e87050', '#f0883e']

interface ConfettiPiece {
  id: number
  left: number
  delay: number
  duration: number
  color: string
  size: number
  round: boolean
}

export function ChallengeSuccess() {
  const challengeSolved = useTamiStore((s) => s.challengeSolved)
  const challengeImageUrl = useTamiStore((s) => s.challengeImageUrl)
  const leaderboardPosition = useTamiStore((s) => s.leaderboardPosition)
  const leaderboardId = useTamiStore((s) => s.leaderboardId)
  const dismissChallenge = useTamiStore((s) => s.dismissChallenge)
  const [name, setName] = useState('')
  const [nameSaved, setNameSaved] = useState(false)
  const [saving, setSaving] = useState(false)

  // Confetti pieces are stable across re-renders
  const confetti: ConfettiPiece[] = useMemo(
    () =>
      Array.from({ length: 20 }, (_, i) => ({
        id: i,
        left: (i / 20) * 100 + Math.random() * 5,
        delay: Math.random() * 1.5,
        duration: 1.5 + Math.random() * 0.5,
        color: CONFETTI_COLORS[i % CONFETTI_COLORS.length],
        size: 6 + Math.floor(Math.random() * 5),
        round: i % 2 === 0,
      })),
    [],
  )

  async function handleSaveName() {
    if (!name.trim() || !leaderboardId) return
    setSaving(true)
    try {
      await api.setLeaderboardName(leaderboardId, name.trim())
      setNameSaved(true)
    } catch {
      // ignore — name stays Anonym
    } finally {
      setSaving(false)
    }
  }

  if (!challengeSolved) return null

  return (
    <div style={{
      position: 'absolute',
      inset: 0,
      background: 'rgba(13,17,23,0.95)',
      borderRadius: 12,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
      overflow: 'hidden',
    }}>
      {/* Confetti — 20 divs */}
      {confetti.map((p) => (
        <div
          key={p.id}
          style={{
            position: 'absolute',
            left: `${p.left}%`,
            top: '-20px',
            width: p.size,
            height: p.size,
            background: p.color,
            borderRadius: p.round ? '50%' : '2px',
            animation: `confettiFall ${p.duration}s ${p.delay}s ease-in infinite`,
          }}
        />
      ))}

      {/* Close button */}
      <button
        onClick={dismissChallenge}
        style={{
          position: 'absolute',
          top: 10,
          right: 12,
          background: 'transparent',
          border: 'none',
          color: 'var(--text-secondary)',
          fontSize: 18,
          cursor: 'pointer',
          lineHeight: 1,
          zIndex: 1,
        }}
        title="Schließen"
      >
        ×
      </button>

      {/* Content */}
      <div style={{
        position: 'relative',
        zIndex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 10,
        padding: '20px 24px',
        textAlign: 'center',
      }}>
        <div style={{ fontSize: 32 }}>🎉</div>
        <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--accent)' }}>
          Du hast Taps gehackt!
        </div>

        {challengeImageUrl && (
          <img
            src={challengeImageUrl}
            alt="Generated by Taps"
            style={{
              maxWidth: 200,
              borderRadius: 8,
              border: '1px solid var(--border-hover)',
            }}
          />
        )}

        {leaderboardPosition !== null && (
          <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
            Du bist Platz #{leaderboardPosition} auf der Bestenliste!
          </div>
        )}

        {/* Name input */}
        {!nameSaved ? (
          <div style={{ display: 'flex', gap: 6, width: '100%', maxWidth: 240 }}>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSaveName()}
              placeholder="Dein Name für die Bestenliste"
              maxLength={80}
              style={{
                flex: 1,
                background: 'var(--bg-tertiary)',
                border: '1px solid var(--border-hover)',
                borderRadius: 4,
                color: 'var(--text-primary)',
                fontSize: 10,
                padding: '4px 8px',
                outline: 'none',
                fontFamily: "'Courier New', Courier, monospace",
              }}
            />
            <button
              onClick={handleSaveName}
              disabled={saving || !name.trim()}
              style={{
                padding: '4px 10px',
                background: name.trim() ? 'var(--accent)' : 'var(--text-hint)',
                color: 'var(--bg-primary)',
                border: 'none',
                borderRadius: 4,
                fontWeight: 700,
                fontSize: 10,
                cursor: name.trim() ? 'pointer' : 'not-allowed',
                fontFamily: "'Courier New', Courier, monospace",
              }}
            >
              {saving ? '...' : 'OK'}
            </button>
          </div>
        ) : (
          <div style={{ fontSize: 10, color: 'var(--accent)' }}>
            ✓ Name gespeichert!
          </div>
        )}

        <button
          onClick={dismissChallenge}
          style={{
            padding: '6px 18px',
            background: 'var(--accent)',
            color: 'var(--bg-primary)',
            border: 'none',
            borderRadius: 4,
            fontWeight: 700,
            fontSize: 11,
            cursor: 'pointer',
            fontFamily: "'Courier New', Courier, monospace",
          }}
        >
          Schließen
        </button>
      </div>
    </div>
  )
}
